services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: abhi@1289
    ports:
      - "5433:5432"

  backend:
    build: ./Backend/deepfake_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=lms_user
      - POSTGRES_PASSWORD=abhi@1289
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - backend_media:/app/media

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_media:
